name: Deploy to MonsterASP.NET

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore HotelEcommerce.sln
      
      - name: Build
        run: dotnet build HotelEcommerce.sln --configuration Release --no-restore -p:TreatWarningsAsErrors=false
      
      - name: Publish
        # CHANGE THIS LINE - replace HotelEcommerce.csproj with YOUR actual project name
        run:  run: dotnet publish "Project(DEPI)/HotelEcomm.csproj" --configuration Release --output ./publish --no-build
      
      - name: Deploy to MonsterASP
        uses: rasmusbuchholdt/simply-web-deploy@2.2.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: './publish/'
